module.exports = {
  apps: [
    {
      name:         "gianauth-backend",
      script:       "./backend/src/index.js",
      cwd:          "./backend",
      instances:    1,
      exec_mode:    "fork",
      env_production: {
        NODE_ENV:  "production",
        PORT:      4000,
      },
      error_file:   "./logs/backend-error.log",
      out_file:     "./logs/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      restart_delay:   3000,
      max_restarts:    10,
      watch:           false,
    },
    {
      name:         "gianauth-frontend",
      script:       "npm",
      args:         "start",
      cwd:          "./frontend",
      instances:    1,
      exec_mode:    "fork",
      env_production: {
        NODE_ENV: "production",
        PORT:     3000,
      },
      error_file:   "./logs/frontend-error.log",
      out_file:     "./logs/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      restart_delay:   3000,
      max_restarts:    10,
      watch:           false,
    },
    {
      name:         "gianauth-bot",
      script:       "./discord-bot/index.js",
      cwd:          "./discord-bot",
      instances:    1,
      exec_mode:    "fork",
      env_production: {
        NODE_ENV: "production",
      },
      error_file:   "./logs/bot-error.log",
      out_file:     "./logs/bot-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      restart_delay:   5000,
      max_restarts:    5,
      watch:           false,
    },
  ],
};
