const { z } = require("zod");

const hexColor = z.string().regex(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/, "Color hex inválido (#RGB o #RRGGBB)").nullable().optional();
const positiveInt = z.coerce.number().int().positive();
const pageQuery = z.object({
  page:  z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(200).default(50),
});

const schemas = {
  // Auth
  login: z.object({
    username: z.string().min(1).max(64),
    password: z.string().min(1).max(128),
  }),

  // Users / branding
  createUser: z.object({
    username: z.string().min(2).max(32).regex(/^[a-zA-Z0-9_]+$/, "Solo letras, números y guión bajo"),
    password: z.string().min(6).max(128),
  }),
  updateBranding: z.object({
    displayName: z.string().max(64).nullable().optional(),
    panelName:   z.string().max(64).nullable().optional(),
    accentColor: hexColor,
    avatarUrl:   z.string().url("URL inválida").max(512).nullable().optional(),
  }),

  updateOwnerProfile: z.object({
    displayName: z.string().max(64).nullable().optional(),
    panelName:   z.string().max(64).nullable().optional(),
    accentColor: hexColor,
    avatarUrl:   z.string().url("URL inválida").max(512).nullable().optional(),
    socialLinks: z.array(
      z.object({
        id:    z.string().uuid().optional(), // generated by backend if missing
        type:  z.enum(["discord","whatsapp","github","telegram","website","custom"]),
        label: z.string().min(1).max(64),
        url:   z.string().url("URL inválida").max(512).refine(
          (u) => /^https?:\/\//i.test(u),
          "Solo se permiten URLs http/https"
        ),
      })
    ).max(10).optional(),
  }),
  updateLimits: z.object({
    maxClaimsDay: z.coerce.number().int().min(0).nullable().optional(),
    maxResetsDay: z.coerce.number().int().min(0).nullable().optional(),
  }),
  updateRenewal: z.object({
    renewalDate:   z.string().datetime({ offset: true }).nullable().optional(),
    renewalStatus: z.enum(["active", "pending", "overdue"]).optional(),
    renewalNote:   z.string().max(256).nullable().optional(),
  }),

  // Licenses
  importLicenses: z.object({
    keys:       z.array(z.string().min(1).max(256)).min(1).max(1000),
    productId:  positiveInt,
    duration:   z.coerce.number().int().min(1).max(3650),
    resellerId: positiveInt,
  }),
  claimLicense: z.object({
    productId: positiveInt,
    duration:  z.coerce.number().int().min(1).max(3650),
  }),
  updatePrivate: z.object({
    resellerPrivateStatus: z.enum(["nueva","entregada","asignada","pendiente_pago","vip","archivada"]).nullable().optional(),
    clientAlias: z.string().max(128).nullable().optional(),
    favorite:    z.boolean().optional(),
  }),
  updateMeta: z.object({
    assignedUser: z.string().max(128).nullable().optional(),
    notes:        z.string().max(1024).nullable().optional(),
  }),

  bulkDeleteLicenses: z.object({
    ids: z.array(z.number().int().positive()).min(1).max(500),
  }),

  // Products
  createProduct: z.object({
    name: z.string().min(1).max(64),
    slug: z.string().min(1).max(32).regex(/^[a-z0-9-]+$/, "Solo minúsculas, números y guiones"),
  }),
  updateProduct: z.object({
    name:   z.string().min(1).max(64).optional(),
    active: z.boolean().optional(),
  }),

  // Requests
  createRequest: z.object({
    licenseId: positiveInt,
    type:      z.enum(["reset_hwid","ban","unban","delete","extend"]),
    comment:   z.string().max(512).optional(),
  }),
  resolveRequest: z.object({
    status:       z.enum(["approved","rejected","completed"]),
    resolvedNote: z.string().max(512).optional(),
  }),

  // Support tickets
  createTicket: z.object({
    subject:  z.string().min(1).max(128),
    message:  z.string().min(1).max(2048),
    priority: z.enum(["low", "medium", "high"]).default("medium"),
  }),
  replyTicket: z.object({
    body: z.string().min(1).max(2048),
  }),
  updateTicket: z.object({
    status:   z.enum(["open", "in_progress", "closed"]).optional(),
    priority: z.enum(["low", "medium", "high"]).optional(),
  }),

  // Logs query
  logsQuery: pageQuery.extend({
    action:     z.string().max(64).optional(),
    actorId:    z.coerce.number().int().optional(),
    targetType: z.enum(["license","user","request","product"]).optional(),
    search:     z.string().max(128).optional(),
    from:       z.string().datetime({ offset: true }).optional(),
    to:         z.string().datetime({ offset: true }).optional(),
  }),

  // Licenses query
  licensesQuery: pageQuery.extend({
    product:  z.coerce.number().int().optional(),
    status:   z.enum(["available","used","blocked","expired"]).optional(),
    duration: z.coerce.number().int().optional(),
    search:   z.string().max(128).optional(),
  }),
};

/**
 * Middleware factory: valida req.body con el schema dado.
 * En caso de error devuelve 400 con los mensajes de Zod.
 */
function validate(schema) {
  return (req, res, next) => {
    const result = schema.safeParse(req.body);
    if (!result.success) {
      const errors = result.error.errors.map((e) => `${e.path.join(".")}: ${e.message}`);
      return res.status(400).json({ error: errors[0], details: errors });
    }
    req.body = result.data;
    next();
  };
}

/**
 * Valida req.query con el schema dado.
 */
function validateQuery(schema) {
  return (req, res, next) => {
    const result = schema.safeParse(req.query);
    if (!result.success) {
      const errors = result.error.errors.map((e) => `${e.path.join(".")}: ${e.message}`);
      return res.status(400).json({ error: errors[0], details: errors });
    }
    req.query = result.data;
    next();
  };
}

module.exports = { schemas, validate, validateQuery };
